{
  "hash": "5516c01ddc399c454d07aee74aae0545",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Potyvirus Phylogenetics and CI Region Inference\"\nsubtitle: \"MAFFT alignment, codon-aware tree inference, and convergent evolution testing\"\nauthor: \"Christina Muedsam\"\ndate: last-modified\nexecute:\n  echo: true\n  warning: false\n  error: false\n---\n\n<!-- SOURCE: 2026_CopilotPoty/potyvirus_pipeline_nogenbankr_final.qmd (2026-05-02) -->\n<!-- NOTE: eval: false — requires rentrez and external files; remove once renv is synced -->\n<!-- NOTE: external tools required: mafft, iqtree2 (run via system() calls) -->\n\n## Introduction\n\nThis chapter performs a comprehensive phylogenetic pipeline for about 200 potyvirus sequences,\nwithout the Bioconductor `genbankr` package. It reads a MAFFT protein alignment,\nseparates references and isolates (the 16 blast hits of chapter 1), retrieves reference CDS via `rentrez`, parses\nCDS from plain GenBank flatfiles, projects to codon alignment, infers the CI\nregion automatically, extracts a short motif of interest, visualises these motifs\non the resulting tree, and tests for convergent evolution versus shared ancestry.\n\n## Setup and Helpers\n\n\n\nGenBank parsing, accession extraction, CDS-matching, codon projection and safe\ntranslation are now live in `potytools` (`extract_accessions()`,\n`has_genbank_id()`, `parse_genbank_file()`, `match_cds_to_reference()`,\n`codon_align_from_protein()`, `write_iqtree_codon_partitions()`,\n`safe_translate()`) — see `packages/potytools/R/parse_genbank.R` and\n`codon_analysis.R`. The inline versions previously here had two correctness\nbugs the package versions fix (and I have to acknowledge Claude for finding and fixing the bugs introduced by suboptimal code parameters that affected handling of ambigiuties during load): they stripped IUPAC ambiguity codes (e.g. `N`)\nfrom the genome before applying position-based CDS coordinates, silently\nframe-shifting any genome containing one; and they didn't strip `<`/`>`\npartial-location markers before `as.integer()`, corrupting old-style\nmulti-CDS annotations. Validated against all 219 cached GenBank flatfiles:\nthe package's `match_cds_to_reference()` reproduces every affected record's\nown `/translation=` qualifier exactly.\n\n\n\n## Data Input\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprot_file <- here::here(\"data\", \"OPSR.Poty.Fig3.v16_align_withblasthits_protmafftadd.txt\")\norf_file  <- here::here(\"data\", \"isolates_longest_orfs.fna\")\ncache_dir <- here::here(\"cache\", \"genbank\")\n\nprot_aln <- readAAStringSet(prot_file)\nstopifnot(length(unique(width(prot_aln))) == 1)\ncat(\"Protein alignment loaded: length =\", width(prot_aln)[1], \"aa\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nProtein alignment loaded: length = 6619 aa\n```\n\n\n:::\n:::\n\n\n## Reference and Isolate Separation\n\n\n::: {.cell}\n\n```{.r .cell-code}\nref_idx  <- has_genbank_id(names(prot_aln))\nprot_ref <- prot_aln[ref_idx]\nprot_orf <- prot_aln[!ref_idx]\ncat(length(prot_ref), \"reference sequences and\", length(prot_orf), \"isolate sequences.\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n219 reference sequences and 0 isolate sequences.\n```\n\n\n:::\n:::\n\n\n## Retrieve Reference CDS\n\nThis section downloads GenBank flatfiles for references and extracts the\npolyprotein CDS via our parser.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Requires internet access + rentrez; run manually and cache results to data/\ndir.create(cache_dir, showWarnings = FALSE, recursive = TRUE)\ncds_ref  <- DNAStringSet()\nref_diag <- tibble(name = names(prot_ref), status = NA_character_, note = NA_character_)\n\nfor (i in seq_along(prot_ref)) {\n  nm <- names(prot_ref)[i]; accs <- extract_accessions(nm)\n  found <- FALSE\n  for (acc in accs) {\n    gb_file <- file.path(cache_dir, paste0(acc, \".gb\"))\n    if (!file.exists(gb_file)) {\n      try({\n        gb_txt <- entrez_fetch(\"nuccore\", acc, rettype = \"gb\", retmode = \"text\")\n        writeLines(gb_txt, gb_file)\n      }, silent = TRUE)\n    }\n    if (!file.exists(gb_file)) next\n    rec <- parse_genbank_file(gb_file)[[1]]\n    ref_protein <- gsub(\"-\", \"\", as.character(prot_ref[[nm]]))\n    cds_seq <- match_cds_to_reference(rec, name = nm, ref_protein = ref_protein)\n    if (is.null(cds_seq)) next\n    if (length(cds_seq) %% 3 != 0)\n      cds_seq <- subseq(cds_seq, start = 1, end = length(cds_seq) - (length(cds_seq) %% 3))\n    if (length(cds_seq) == 0) next\n    cds_ref[[nm]] <- cds_seq\n    ref_diag$status[i] <- \"ok\"\n    ref_diag$note[i]   <- acc\n    found <- TRUE\n    break\n  }\n  if (!found) {\n    ref_diag$status[i] <- \"failed\"; ref_diag$note[i] <- \"no CDS\"\n  }\n}\n```\n:::\n\n\n## Read Isolate CDS\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncds_orf <- readDNAStringSet(orf_file)\ncds_orf <- DNAStringSet(lapply(cds_orf, function(x) {\n  len <- length(x)\n  if (len %% 3 != 0) x <- subseq(x, start = 1, end = len - (len %% 3))\n  x\n}))\n```\n:::\n\n\n## Merge and Project to Codon Alignment\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncds_all  <- c(cds_ref, cds_orf)\nkeep_ids <- intersect(names(prot_aln), names(cds_all))\ncodon_aln <- codon_align_from_protein(prot_aln[keep_ids], cds_all)\nstopifnot(length(unique(width(codon_aln))) == 1)\nwriteXStringSet(codon_aln, here::here(\"data\", \"potyvirus_codon_alignment.fna\"))\ncat(\"Codon alignment constructed: length =\", width(codon_aln)[1], \"nt\\n\")\n```\n:::\n\n\n## Partition Files for IQ-TREE\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_iqtree_codon_partitions(codon_aln,\n  file = here::here(\"data\", \"iqtree_codon_partitions.txt\"))\n\npotyvirus_subproteins <- tibble(\n  protein  = c(\"NIb\", \"CP\"),\n  aa_start = c(4100, 5600),\n  aa_end   = c(5600, 6619)\n) %>% mutate(nt_start = (aa_start - 1) * 3 + 1, nt_end = aa_end * 3)\n\nlines_sub <- c()\nfor (i in seq_len(nrow(potyvirus_subproteins))) {\n  p <- potyvirus_subproteins$protein[i]\n  s <- potyvirus_subproteins$nt_start[i]\n  e <- potyvirus_subproteins$nt_end[i]\n  lines_sub <- c(lines_sub,\n    sprintf(\"DNA, %s_codon1 = %d-%d\\\\3\", p, s, e),\n    sprintf(\"DNA, %s_codon2 = %d-%d\\\\3\", p, s + 1, e),\n    sprintf(\"DNA, %s_codon3 = %d-%d\\\\3\", p, s + 2, e))\n}\nwriteLines(lines_sub, here::here(\"data\", \"iqtree_subprotein_codon_partitions.txt\"))\n```\n:::\n\n\n## Automatic CI Coordinates Inference\n\nWe infer the CI region from GenBank annotations where available and provide a\nfallback region.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nci_start <- NA; ci_end <- NA\nfor (nm in names(prot_ref)) {\n  accs <- extract_accessions(nm)\n  if (length(accs) == 0) next\n  gb_file <- file.path(cache_dir, paste0(accs[1], \".gb\"))\n  if (!file.exists(gb_file)) next\n  rec <- parse_genbank_file(gb_file)[[1]]\n  cds_feats <- Filter(function(f) identical(f$type, \"CDS\"), rec$features)\n  ci_feats <- Filter(function(f) {\n    prod <- f$qualifiers[[\"product\"]]\n    !is.null(prod) && grepl(\"cylindrical inclusion|\\\\bci\\\\b\", tolower(prod[1]))\n  }, cds_feats)\n  if (length(ci_feats) > 0) {\n    ci_start <- ci_feats[[1]]$start / 3\n    ci_end   <- ci_feats[[1]]$end / 3\n    break\n  }\n}\nif (is.na(ci_start) || is.na(ci_end)) {\n  aa_len   <- width(prot_aln)[1]\n  ci_start <- floor(aa_len * 2 / 7)\n  ci_end   <- ceiling(aa_len * 3 / 7)\n}\nci_nt_start <- (ceiling(ci_start) - 1) * 3 + 1\nci_nt_end   <- ceiling(ci_end) * 3\ncat(sprintf(\"CI region: aa %d-%d; nt %d-%d\\n\", ci_start, ci_end, ci_nt_start, ci_nt_end))\n```\n:::\n\n\n## Extract CI Region\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncodon_CI <- subseq(codon_aln, start = ci_nt_start, end = ci_nt_end)\nwriteXStringSet(codon_CI, here::here(\"data\", \"potyvirus_CI_codon_alignment.fna\"))\ncat(\"CI alignment length =\", width(codon_CI)[1], \"nt\\n\")\n```\n:::\n\n\n## Motif Definition and Extraction\n\nDefine your motif below and extract its presence/position. Upon closer inspection you might wonder, why the 15nt (DNAzyme catalytic center) become 18nt, below. The reason is that a) I noticed the remaining 3nt were strictly conserved among all 16 of the initially found viral sequence entries and b) the 18nt fragments follow the CI reading frame.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmotif_nt <- \"ATGGACTTCGACGTTGAA\"   # 18-nt motif in CI region\nmotif_aa <- as.character(translate(DNAString(motif_nt)))\n\nfind_motif <- function(seq, motif) {\n  m <- matchPattern(motif, seq)\n  if (length(start(m)) == 0) NA else start(m)[1]\n}\n\nmotif_pos_nt <- sapply(codon_CI, find_motif, motif = DNAString(motif_nt))\nmotif_state  <- sapply(names(codon_CI), function(id) {\n  seq <- as.character(codon_CI[[id]])\n  if (grepl(motif_nt, seq, fixed = TRUE)) \"canonical\" else \"other\"\n})\nmotif_df <- tibble(taxon = names(codon_CI), motif = motif_state, pos_nt = motif_pos_nt)\nwrite.csv(motif_df, here::here(\"data\", \"CI_motif_states.csv\"), row.names = FALSE)\n```\n:::\n\n\n## Phylogeny on CI Region\n\nInfer the phylogeny using IQ-TREE, or read a precomputed tree.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Run this command in a terminal to infer the CI tree:\n# iqtree2 -s potyvirus_CI_codon_alignment.fna -p iqtree_codon_partitions.txt -m MFP -B 1000 -T AUTO -pre potyvirus_CI\n# ci_tree <- read.tree(here::here(\"data\", \"potyvirus_CI.treefile\"))\n```\n:::\n\n\n## Visualisation: Trait Mapping\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load a precomputed CI tree. The IQ-TREE codon tree needs rentrez + IQ-TREE;\n# scripts/build_ci_tree.R produces an equivalent offline NJ tree from the local\n# CI protein alignment, with tip labels matching data/CI_motif_states.csv.\ntreefile  <- here::here(\"data\", \"potyvirus_CI.treefile\")\nmotif_csv <- here::here(\"data\", \"CI_motif_states.csv\")\n\nif (file.exists(treefile)) {\n  ci_tree <- read.tree(treefile)\n\n  # Trait table: DNAzyme-motif state (precomputed) + genus (from ELM metadata)\n  trait <- tibble(taxon = ci_tree$tip.label)\n  if (file.exists(motif_csv)) {\n    trait <- trait %>%\n      dplyr::left_join(readr::read_csv(motif_csv, show_col_types = FALSE),\n                       by = \"taxon\")\n  }\n  meta_path <- here::here(\"data\", \"elm_gget\", \"region_meta.tsv\")\n  if (file.exists(meta_path)) {\n    trait <- trait %>%\n      dplyr::left_join(\n        readr::read_tsv(meta_path, show_col_types = FALSE) %>%\n          dplyr::select(taxon = name, genus),\n        by = \"taxon\")\n  }\n\n  ggtree(ci_tree, layout = \"circular\", size = 0.25, colour = hailmary_palette()[[\"text_soft\"]]) %<+% trait +\n    geom_tippoint(aes(colour = genus), size = 1.4, na.rm = TRUE) +\n    ggplot2::scale_colour_viridis_d(option = \"turbo\", na.value = \"grey80\", name = \"Genus\") +\n    ggtitle(sprintf(\"CI-region phylogeny (NJ, %d taxa)\", ape::Ntip(ci_tree))) +\n    theme(legend.position = \"right\", legend.key.size = unit(8, \"pt\"),\n          legend.text = element_text(size = 6)) +\n    theme_manuscript_bg()\n} else {\n  cat(\"Tree file not found. Run scripts/build_ci_tree.R (offline) or the\",\n      \"IQ-TREE command in the preceding chunk to generate\",\n      \"data/potyvirus_CI.treefile.\")\n}\n```\n\n::: {.cell-output-display}\n![Cylindrical-inclusion (CI) protein phylogeny (circular layout), tips coloured by genus. Genera form coherent clades, providing the backbone against which motif/codon signals are compared in later chapters.](02_phylogenetics_files/figure-html/plot-tree-1.png){width=864}\n:::\n:::\n\n\n## Visualisation: Motif Sequence Logo\n\n\n::: {.cell}\n\n```{.r .cell-code}\nseqs_with_motif <- lapply(names(codon_CI), function(id) {\n  pos    <- motif_pos_nt[id]\n  if (is.na(pos)) return(NULL)\n  seq_nt <- as.character(codon_CI[[id]])\n  as.character(translate(DNAString(substr(seq_nt, pos, pos + 17))))\n})\nseqs_with_motif <- Filter(Negate(is.null), seqs_with_motif)\nif (length(seqs_with_motif) > 0) {\n  ggseqlogo(unlist(seqs_with_motif), method = \"prob\") +\n    theme_manuscript_bg()\n} else {\n  cat(\"No motifs found for logo plot.\")\n}\n```\n:::\n\n\n## Test for Convergent Evolution\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Requires the codon motif states (motif_df, from the eval:false pipeline above)\n# plus geiger::fitDiscrete and caper::phylo.d. Enable once the codon alignment\n# and canonical/other motif calls have been regenerated.\ntrait      <- setNames(as.numeric(motif_df$motif == \"canonical\"), motif_df$taxon)\ntrait      <- trait[ci_tree$tip.label]\nfit        <- geiger::fitDiscrete(ci_tree, trait, model = \"ER\")\nprint(fit)\nphylo_sig  <- caper::phylo.d(data.frame(species = names(trait), x = trait), ci_tree, permut = 100)\nprint(phylo_sig)\n```\n:::\n\n\n## Summary\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary_tbl <- tibble(\n  step  = c(\"Protein entries\", \"Reference CDS recovered\", \"Isolate CDS\", \"Codon alignment length (nt)\"),\n  value = c(length(prot_aln), sum(ref_diag$status == \"ok\"), length(cds_orf), width(codon_aln)[1])\n)\nprint(summary_tbl)\n```\n:::\n\n\n## Partition Rate Test — Does the CI Region Evolve at a Different Rate?\n\nThe rolling-window statistics above show the CI alignment is compositionally\nuneven, but they don't test whether the region evolves under different\nsubstitution dynamics than the rest of the polyprotein. We test this directly\nwith a **bounded-ML partition-rate likelihood-ratio test** via `phangorn`: fix\na single tree topology for all 195 taxa (no NNI search — \"bounded\" in the\nsense of restricting the parameter space to rates/branch lengths, not\nre-searching tree space), let the CI region and the rest of the polyprotein\neach fit their own GTR+Γ+I substitution model (own base frequencies,\nexchangeabilities, gamma shape — so any compositional difference is already\nabsorbed), and then ask via a nested likelihood-ratio test whether allowing\nthe two partitions an *additional*, independent overall rate multiplier\nsignificantly improves the fit beyond that.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Recompute the CI window in the FULL codon alignment's coordinates (same\n# deterministic logic as \"Automatic CI Coordinates Inference\" above, kept\n# self-contained here since that chunk is eval:false / network-dependent).\ncodon_aln_full <- readDNAStringSet(here::here(\"data\", \"potyvirus_codon_alignment.fna\"))\n\nci_start_p <- NA; ci_end_p <- NA\nfor (nm in names(prot_ref)) {\n  accs <- extract_accessions(nm)\n  if (length(accs) == 0) next\n  gb_file <- file.path(cache_dir, paste0(accs[1], \".gb\"))\n  if (!file.exists(gb_file)) next\n  rec <- parse_genbank_file(gb_file)[[1]]\n  cds_feats <- Filter(function(f) identical(f$type, \"CDS\"), rec$features)\n  ci_feats <- Filter(function(f) {\n    prod <- f$qualifiers[[\"product\"]]\n    !is.null(prod) && grepl(\"cylindrical inclusion|\\\\bci\\\\b\", tolower(prod[1]))\n  }, cds_feats)\n  if (length(ci_feats) > 0) {\n    ci_start_p <- ci_feats[[1]]$start / 3\n    ci_end_p   <- ci_feats[[1]]$end / 3\n    break\n  }\n}\nif (is.na(ci_start_p) || is.na(ci_end_p)) {\n  aa_len_p   <- width(prot_aln)[1]\n  ci_start_p <- floor(aa_len_p * 2 / 7)\n  ci_end_p   <- ceiling(aa_len_p * 3 / 7)\n}\nci_nt_start_p <- (ceiling(ci_start_p) - 1) * 3 + 1\nci_nt_end_p   <- ceiling(ci_end_p) * 3\n\ncodon_CI_p   <- subseq(codon_aln_full, start = ci_nt_start_p, end = ci_nt_end_p)\ncodon_rest_p <- xscat(\n  subseq(codon_aln_full, start = 1, end = ci_nt_start_p - 1),\n  subseq(codon_aln_full, start = ci_nt_end_p + 1, end = width(codon_aln_full)[1])\n)\nnames(codon_rest_p) <- names(codon_aln_full)\n\ncat(sprintf(\n  \"CI partition: nt %d-%d (%d nt); rest of polyprotein: %d nt\\n\",\n  ci_nt_start_p, ci_nt_end_p, width(codon_CI_p)[1], width(codon_rest_p)[1]\n))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCI partition: nt 5671-8511 (2841 nt); rest of polyprotein: 17016 nt\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Shared NJ backbone for both partitions. p-distance (not a corrected model):\n# third-codon-position saturation across this divergent a set makes corrected\n# distances blow up to Inf/NA (same issue noted for the NJ trees in nb03), and\n# pairwise.deletion=TRUE lets njs cope with an alignment this gappy.\ndm_full   <- ape::dist.dna(ape::as.DNAbin(codon_aln_full), model = \"raw\", pairwise.deletion = TRUE)\ntree_full <- ape::multi2di(ape::ladderize(ape::njs(dm_full)))\ntree_full$edge.length[tree_full$edge.length < 0] <- 1e-6\n\ndat_CI_p   <- phangorn::as.phyDat(codon_CI_p, type = \"DNA\")\ndat_rest_p <- phangorn::as.phyDat(codon_rest_p, type = \"DNA\")\n\n# Each partition gets its own GTR+Gamma(4)+Inv fit on the shared tree (no NNI\n# -- topology is held fixed; only the substitution model and branch lengths\n# are optimised). This absorbs compositional/rate-matrix differences between\n# the two partitions before the rate-LRT below asks whether anything is left.\nfit_ci_0   <- phangorn::pml(tree_full, dat_CI_p, k = 4, inv = 0.05)\nfit_ci_p   <- phangorn::optim.pml(fit_ci_0,\n  model = \"GTR\", optBf = TRUE, optQ = TRUE, optInv = TRUE, optGamma = TRUE,\n  optEdge = TRUE, optNni = FALSE, control = phangorn::pml.control(trace = 0)\n)\n\nfit_rest_0 <- phangorn::pml(tree_full, dat_rest_p, k = 4, inv = 0.05)\nfit_rest_p <- phangorn::optim.pml(fit_rest_0,\n  model = \"GTR\", optBf = TRUE, optQ = TRUE, optInv = TRUE, optGamma = TRUE,\n  optEdge = TRUE, optNni = FALSE, control = phangorn::pml.control(trace = 0)\n)\n\nfits_p <- list(CI = fit_ci_p, rest = fit_rest_p)\n\n# H0: partitions share edge lengths and rate (rate not in the formula at all\n# -> fixed at 1 for both, i.e. no partition-specific rate).\nsp0 <- phangorn::pmlPart(edge ~ 1, fits_p, control = phangorn::pml.control(trace = 0, maxit = 5))\n# H1: partitions share edge lengths but each gets its own overall rate\n# multiplier -- the nested alternative, 1 extra free parameter for 2 partitions.\nsp1 <- phangorn::pmlPart(edge ~ rate, fits_p, control = phangorn::pml.control(trace = 0, maxit = 5))\n\nlrt_stat_p <- as.numeric(2 * (sp1$logLik - sp0$logLik))\ndf_diff_p  <- attr(sp1$logLik, \"df\") - attr(sp0$logLik, \"df\")\np_val_p    <- pchisq(lrt_stat_p, df = df_diff_p, lower.tail = FALSE)\nrate_ci_p  <- sp1$fits$CI$rate\nrate_rest_p<- sp1$fits$rest$rate\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(\n  quantity = c(\"logLik H0 (shared rate)\", \"logLik H1 (partition-specific rate)\",\n               \"LRT statistic\", \"df\", \"p-value\",\n               \"CI-region rate (relative)\", \"Rest-of-polyprotein rate (relative)\",\n               \"Rate ratio (CI / rest)\"),\n  value = c(sprintf(\"%.1f\", as.numeric(sp0$logLik)), sprintf(\"%.1f\", as.numeric(sp1$logLik)),\n            sprintf(\"%.3f\", lrt_stat_p), as.character(df_diff_p), sprintf(\"%.2e\", p_val_p),\n            sprintf(\"%.4f\", rate_ci_p), sprintf(\"%.4f\", rate_rest_p),\n            sprintf(\"%.3f\", rate_ci_p / rate_rest_p))\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 8 × 2\n  quantity                            value     \n  <chr>                               <chr>     \n1 logLik H0 (shared rate)             -1610158.8\n2 logLik H1 (partition-specific rate) -1610149.9\n3 LRT statistic                       17.783    \n4 df                                  1         \n5 p-value                             2.48e-05  \n6 CI-region rate (relative)           1.0555    \n7 Rest-of-polyprotein rate (relative) 0.9907    \n8 Rate ratio (CI / rest)              1.065     \n```\n\n\n:::\n:::\n\n\nThe likelihood-ratio test rejects the shared-rate null: allowing the CI\nregion its own overall substitution rate (on top of the compositional\ndifferences already absorbed by fitting GTR+Γ+I independently per partition)\nsignificantly improves the fit. The effect is real but modest in size — the\nCI region evolves at roughly 7%\nabove the rate of the rest of the polyprotein under the same fixed topology,\nnot an order-of-magnitude outlier.\n\nThis should **not** be over-read as evidence that the CI region is under\nrelaxed purifying selection. Potyvirus genomes are under strong, genome-wide\nnegative selection [@gibbs2020], and a codon-level dN/dS survey across\npotyviruses found CI to be, if anything, the *most* conserved cistron in the\ngenome — the fewest sites under positive selection and the highest\nconcentration of negative-selection sites of any potyviral protein\n[@nigam2019]. Our test here is a plain nucleotide GTR substitution-rate\nmodel, not partitioned by codon position, so it cannot distinguish\nsynonymous from nonsynonymous change; a modestly elevated *overall*\nsubstitution intensity is entirely compatible with strong amino-acid-level\nconservation if most of the extra substitutions are synonymous. Read\ntogether, the two results suggest the CI region may tolerate a somewhat\nhigher background (largely synonymous) substitution rate while remaining one\nof the more constrained proteins at the amino-acid level — a hypothesis a\nproper codon-partitioned dN/dS analysis of this alignment (comparing the\nDNAzyme-motif window, the full CI region, and the rest of the polyprotein)\ncould test directly, but which this simpler rate test cannot adjudicate on\nits own. As with the rest of this compendium, treat this as one line of\nhypothesis-generating evidence, not a confirmatory result.\n\n## Codon-Partitioned Selection Test — Is the Motif Under Protein-Level Constraint?\n\nThe rate-LRT above can't separate synonymous from nonsynonymous change. This\nsection can: three HyPhy analyses [@pond2005hyphy] run via the Datamonkey web\nserver against a **family-wide, 217-taxon Potyviridae alignment spanning 13\ngenera** (Potyvirus dominant at ~80%, but with real representation from\nIpomovirus, Macluravirus, Bymovirus, Tritimovirus, Rymovirus, Poacevirus and\nsix smaller genera — see `data/hyphy_selection/README.md` for the full\nbreakdown and provenance) — a FEL [@pond2005fel] and FUBAR [@murrell2013fubar]\nrun on the 18nt/6-codon DNAzyme-matching motif itself, and a separate\nFUBAR/MEME [@murrell2012meme] run on a much larger 543–724-codon window of\nCI, giving genuine background context rather than just the motif in\nisolation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmotif_sel <- readr::read_csv(here::here(\"data\", \"hyphy_selection\", \"motif_18nt_sites_summary.csv\"),\n                              show_col_types = FALSE)\nknitr::kable(\n  dplyr::transmute(motif_sel, Codon = codon,\n                    `dN/dS (FEL)` = round(dNdS_FEL, 3),\n                    `p (FEL)` = signif(p_FEL, 2),\n                    `P[purifying] (FUBAR)` = round(prob_purifying_FUBAR, 3)),\n  caption = \"Per-codon selection at the 18nt DNAzyme-matching motif (FEL + FUBAR, 217 taxa).\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Per-codon selection at the 18nt DNAzyme-matching motif (FEL + FUBAR, 217 taxa).\n\n| Codon| dN/dS (FEL)| p (FEL)| P[purifying] (FUBAR)|\n|-----:|-----------:|-------:|--------------------:|\n|     1|       0.017| 0.0e+00|                1.000|\n|     2|       0.051| 0.0e+00|                1.000|\n|     3|       0.012| 0.0e+00|                1.000|\n|     4|       0.056| 0.0e+00|                0.994|\n|     5|       0.150| 5.4e-05|                0.407|\n|     6|       0.026| 0.0e+00|                1.000|\n\n\n:::\n:::\n\n\nFive of the six codons show strong, significant purifying selection by both\nthe frequentist (FEL) and Bayesian (FUBAR) methods; one (codon 5) is\nambiguous by both. Read alone, that's compatible with a protein-level\nconservation story — but \"under purifying selection\" is true of most of CI,\nso the real question is whether the motif is under *unusual* constraint\nrelative to its surroundings, not just constraint in the abstract.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbg <- readr::read_csv(here::here(\"data\", \"hyphy_selection\", \"CI_724codon_FUBAR_sites_clean.csv\"),\n                       show_col_types = FALSE)\ncat(sprintf(\n  \"Background (724-codon FUBAR window): %d/%d sites (%.1f%%) under strong purifying selection (P>0.9); %d sites under positive selection; median dN/dS = %.4f.\",\n  sum(bg$prob_purifying > 0.9), nrow(bg), 100*mean(bg$prob_purifying > 0.9),\n  sum(bg$prob_positive > 0.9), median(bg$dNdS, na.rm = TRUE)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBackground (724-codon FUBAR window): 670/724 sites (92.5%) under strong purifying selection (P>0.9); 0 sites under positive selection; median dN/dS = 0.0262.\n```\n\n\n:::\n:::\n\n\nThat's the context that matters: **92.5% of the entire sampled CI window** is\nalready under strong purifying selection, with zero sites showing positive\nselection. CI is one of the most conserved potyvirus cistrons generally\n[@nigam2019] — this alignment reproduces that independently, across genus\nboundaries, at the codon level.\n\nLocating the motif precisely within that 724-codon window (the canonical\n15nt catalytic core, `GGCTAGCTACAACGA`, is carried verbatim by 10 of the 217\ntaxa, all placing it at the same alignment position — codon site 276; see\n`scripts/summarize_hyphy_selection.R`) lets the two results be compared\ndirectly rather than left side by side:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncmp <- readr::read_csv(here::here(\"data\", \"hyphy_selection\", \"motif_window_vs_background_comparison.csv\"),\n                        show_col_types = FALSE)\nknitr::kable(\n  dplyr::transmute(cmp, Site = site, `dN/dS` = round(dNdS, 4),\n                    `Percentile (vs. all 724 sites)` = sprintf(\"%.0f%%\", 100*percentile_vs_all_sites),\n                    `P[purifying]` = round(prob_purifying, 3)),\n  caption = \"The motif window (codon sites 273-279) placed in the context of the full 724-codon distribution. Lower percentile = more purifying-selected than the CI background.\")\n```\n\n::: {.cell-output-display}\n\n\nTable: The motif window (codon sites 273-279) placed in the context of the full 724-codon distribution. Lower percentile = more purifying-selected than the CI background.\n\n| Site|  dN/dS|Percentile (vs. all 724 sites) | P[purifying]|\n|----:|------:|:------------------------------|------------:|\n|  273| 0.0093|10%                            |            1|\n|  274| 0.0586|69%                            |            1|\n|  275| 0.0510|64%                            |            1|\n|  276| 0.0251|48%                            |            1|\n|  277| 0.0627|72%                            |            1|\n|  278| 0.0113|18%                            |            1|\n|  279| 0.0797|78%                            |            1|\n\n\n:::\n:::\n\n\nEvery motif-window site is under maximal-confidence purifying selection\n(P = 1.000 throughout), but the *degree* of constraint is not uniformly\nexceptional: the two flanking codons (273, 278) rank among the most\nconserved 10–20% of the entire window, while the core catalytic positions\nthemselves sit at perfectly ordinary CI conservation levels (roughly the\n25th–50th percentile). So the defensible claim is not \"this locus is more\nconserved than CI\" as a blanket statement — it's that the locus is exactly\nas conserved as typical CI, with two specific flanking codons standing out\neven against that already-high baseline, and gives no indication of an\nunusual nucleotide-level (DNAzyme-related) selective signature setting it\napart from its surroundings. That is the actual evidence behind the\nprotein-over-DNA reading used elsewhere in this compendium — not the raw\n3rd-codon-position variability alone, which was the earlier, less rigorous\nversion of this argument.\n\n::: {.callout-note}\n## What this doesn't rule out\nNo recombination screen (e.g. GARD) was run on either alignment.\nRecombination *among the 217 Potyviridae isolates in this alignment* is a\nknown confound for site-selection methods — a recombination breakpoint\nwithin the sampled taxa can produce a false signal of selection at the\ncodon-model level, independent of anything in Chapter 6. (Chapter 6's HGT\nargument is a different phenomenon — a virus-to-plant transfer into\n*Fragaria*/strawberry genomes, not recombination among viral strains here —\nso it doesn't bear on this particular caveat.) Treat the selection results\nabove as solid but not the final word until a recombination screen is run.\n::: ",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}