#!/usr/bin/env bash
# fetch_fonts.sh — vendor the book's four webfonts so the site is self-contained.
# Run once from the repo root (Git Bash or WSL): bash scripts/fetch_fonts.sh
#
# Generates assets/fonts.css from Google's own CSS2 response, so @font-face
# blocks carry authoritative unicode-range values rather than guesses. That
# matters here: the chapters use Φ (U+03A6) in YXXΦ, so the greek subset must
# be present and correctly range-gated or Φ falls back mid-word.
set -euo pipefail

FONT_DIR="assets/fonts"; CSS_OUT="assets/fonts.css"
API="https://fonts.googleapis.com/css2?family=Spectral:ital,wght@0,300;0,400;0,500;1,300;1,400&family=Michroma&family=Spline+Sans:wght@300;400;500;600&family=IBM+Plex+Mono:wght@400;500&display=swap"
# Google serves woff2 only to a UA it recognises as modern.
UA="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"

mkdir -p "$FONT_DIR"
echo "==> fetching @font-face manifest"
manifest="$(curl -fsSL -H "User-Agent: $UA" "$API")"
[ -n "$manifest" ] || { echo "error: empty response" >&2; exit 1; }

# Flatten each @font-face block to one record; unicode-range is always last.
records="$(printf '%s\n' "$manifest" | awk '
  /^\/\*/ { l=$0; gsub(/^\/\*[[:space:]]*|[[:space:]]*\*\/$/,"",l);
            gsub(/[^a-zA-Z0-9]+/,"-",l); subset=tolower(l); next }
  /font-family:/ { if (match($0,/'"'"'[^'"'"']+'"'"'/))
                     family=substr($0,RSTART+1,RLENGTH-2); next }
  /font-style:/  { style=$2;  sub(/;.*/,"",style);  next }
  /font-weight:/ { weight=$2; sub(/;.*/,"",weight); next }
  /src:/ { if (match($0,/https:[^)]+/)) url=substr($0,RSTART,RLENGTH); next }
  /unicode-range:/ { r=$0; sub(/^[[:space:]]*unicode-range:[[:space:]]*/,"",r);
                     sub(/;[[:space:]]*$/,"",r);
                     print family"|"style"|"weight"|"subset"|"url"|"r }
')"
[ -n "$records" ] || { echo "error: parsed no @font-face blocks" >&2; exit 1; }

cat > "$CSS_OUT" <<'HEADER'
/* fonts.css — GENERATED by scripts/fetch_fonts.sh. Do not edit by hand.
   Self-hosted faces, all SIL Open Font License 1.1 (texts in assets/fonts/). */
HEADER

while IFS='|' read -r family style weight subset url range; do
  [ -n "$url" ] || continue
  slug="$(printf '%s' "$family" | tr '[:upper:]' '[:lower:]' \
          | tr -c 'a-z0-9' '-' | sed 's/-\{2,\}/-/g; s/^-//; s/-$//')"
  suffix=""; [ "$style" = "italic" ] && suffix="i"
  file="${slug}-${weight}${suffix}-${subset}.woff2"
  [ -f "$FONT_DIR/$file" ] || { printf '    %s\n' "$file"
    curl -fsSL -H "User-Agent: $UA" -o "$FONT_DIR/$file" "$url"; }
  cat >> "$CSS_OUT" <<EOF

@font-face {
  font-family: '${family}';
  font-style: ${style};
  font-weight: ${weight};
  font-display: swap;
  src: url('fonts/${file}') format('woff2');
  unicode-range: ${range};
}
EOF
done <<< "$records"

echo "==> fetching OFL licence texts"
for p in "spectral:Spectral" "michroma:Michroma" "splinesans:Spline-Sans" "ibmplexmono:IBM-Plex-Mono"; do
  d="${p%%:*}"; n="${p##*:}"
  curl -fsSL -o "$FONT_DIR/${n}-OFL.txt" \
    "https://raw.githubusercontent.com/google/fonts/main/ofl/${d}/OFL.txt" \
    || echo "    WARNING: licence for $n not fetched — get it before publishing" >&2
done
echo "==> done"
